-- MySQL Script generated by MySQL Workbench
-- Tue Jan 26 12:00:04 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema TrackCatDB
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `TrackCatDB` ;

-- -----------------------------------------------------
-- Schema TrackCatDB
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `TrackCatDB` DEFAULT CHARACTER SET utf8 ;
USE `TrackCatDB` ;

-- -----------------------------------------------------
-- Table `TrackCatDB`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCatDB`.`users` ;

CREATE TABLE IF NOT EXISTS `TrackCatDB`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `image` MEDIUMTEXT NULL DEFAULT NULL,
  `dateOfBirth` BIGINT(20) NULL DEFAULT NULL,
  `gender` TINYINT(1) NULL DEFAULT NULL,
  `weight` FLOAT NULL DEFAULT NULL,
  `size` FLOAT NULL DEFAULT NULL,
  `darkTheme` TINYINT(1) NOT NULL,
  `hints` TINYINT(1) NOT NULL,
  `dateOfRegistration` BIGINT(20) NOT NULL,
  `lastLogin` BIGINT(20) NOT NULL,
  `timeStamp` BIGINT(20) NOT NULL,
  `verifyToken` VARCHAR(100) NULL DEFAULT NULL,
  `resetToken` VARCHAR(100) NULL,
  `sessionTime` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `eMail_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TrackCatDB`.`liveRecords`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCatDB`.`liveRecords` ;

CREATE TABLE IF NOT EXISTS `TrackCatDB`.`liveRecords` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `time` INT(11) NOT NULL DEFAULT 0,
  `type` INT(11) NOT NULL DEFAULT 0,
  `rideTime` INT(11) NOT NULL DEFAULT 0,
  `distance` DOUBLE NOT NULL DEFAULT 0,
  `users_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_liveRecords_users1_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_liveRecords_users1`
    FOREIGN KEY (`users_id`)
    REFERENCES `TrackCatDB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TrackCatDB`.`locations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCatDB`.`locations` ;

CREATE TABLE IF NOT EXISTS `TrackCatDB`.`locations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `altitude` DOUBLE NOT NULL,
  `time` BIGINT(20) NOT NULL,
  `speed` FLOAT NOT NULL,
  `record_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_route1_idx` (`record_id` ASC) VISIBLE,
  CONSTRAINT `fk_location_liveRecords`
    FOREIGN KEY (`record_id`)
    REFERENCES `TrackCatDB`.`liveRecords` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 1256
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TrackCatDB`.`records`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCatDB`.`records` ;

CREATE TABLE IF NOT EXISTS `TrackCatDB`.`records` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `time` INT(11) NOT NULL,
  `date` BIGINT(20) NOT NULL,
  `type` INT(11) NOT NULL,
  `rideTime` INT(11) NOT NULL,
  `distance` DOUBLE NOT NULL,
  `timeStamp` BIGINT(20) NOT NULL,
  `users_id` INT(11) NOT NULL,
  `locations` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_route_users_idx` (`users_id` ASC) VISIBLE,
  CONSTRAINT `fk_route_users0`
    FOREIGN KEY (`users_id`)
    REFERENCES `TrackCatDB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 20
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `TrackCatDB`.`users_has_users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `TrackCatDB`.`users_has_users` ;

CREATE TABLE IF NOT EXISTS `TrackCatDB`.`users_has_users` (
  `asker` INT(11) NOT NULL,
  `asked` INT(11) NOT NULL,
  `dateOfFriendship` BIGINT(20) NULL,
  `areFriends` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`asker`, `asked`),
  INDEX `fk_users_has_users_users2_idx` (`asked` ASC) VISIBLE,
  INDEX `fk_users_has_users_users1_idx` (`asker` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_users_users1`
    FOREIGN KEY (`asker`)
    REFERENCES `TrackCatDB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_users_users2`
    FOREIGN KEY (`asked`)
    REFERENCES `TrackCatDB`.`users` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
